name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: |
        chmod +x install.sh
        install.sh
        mvn clean install

      - uses: codecov/codecov-action@v1.0.14
