name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: |
          cd lib
          git clone https://github.com/rocogamer/FabledSkyBlock.git
          cd FabledSkyBlock
          git fetch
          git switch patch-1
          git fetch
          git pull
          mvn clean install
          cd ..
          mvn clean install

      - uses: codecov/codecov-action@v1.0.14

      - uses: actions/upload-artifact@v2.2.2
        with:
          name: shiruka
          path: target/InfumiaPlugin.jar
